#!/bin/bash

cargo build --release
cd ./target/release
tar czf autocisco-mac.tar.gz autocisco
shasum -a 256 autocisco-mac.tar.gz | pbcopy
echo "SHA256: $(pbpaste)"
cd -
git add . && git commit -m "fixed bugs. added other bugs to fix later." && git push -u origin master
